"""create eod_summaries table

Revision ID: e847dfe3f398
Revises: f1ff92f6088f
Create Date: 2026-07-03 17:19:43.232441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e847dfe3f398'
down_revision: Union[str, Sequence[str], None] = 'f1ff92f6088f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eod_summaries', 'tomorrow_plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eod_summaries', 'tomorrow_plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
